[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dreamcoat"
description = "The joyful oceanographic seagoing expedition planning helper"
readme = "README.md"
dependencies = [
    "calkulate",
    "cartopy",
    "fsspec",
    "great_circle_calculator",
    "keyring",
    "koolstof",
    "matplotlib",
    "motuclient",
    "napari",
    "netcdf4",
    "numpy",
    "scipy",
    "xarray",
    "yagmail",
    "zarr",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "dreamcoat.__version__"}
