[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dreamcoat"
description = "The joyful oceanographic seagoing expedition planning helper"
readme = "README.md"
dependencies = [
    "cartopy",
    "keyring",
    "matplotlib",
    "motuclient",
    "xarray",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "dreamcoat.__version__"}
